# Generated by Django 4.0.1 on 2022-02-26 12:02

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cve_task_vendor_product"),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vendors"], name="ix_cves_vendors"
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cwes"], name="ix_cves_cwes"
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("summary"),
                    name="gin_trgm_ops",
                ),
                name="ix_cves_summary",
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("cve_id"), name="gin_trgm_ops"
                ),
                name="ix_cves_cve_id",
            ),
        ),
    ]
