# Generated by Django 4.0.1 on 2022-02-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_product_vendor_cve_ix_cves_vendors_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
