# Generated by Django 4.0.1 on 2022-02-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="year_in_school",
            new_name="type",
        ),
    ]
